version: "3.9"

services:
  frontend:
    container_name: pf-planta-pate-web
    image: pf_planta_pate_web-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      NODE_ENV: production
      PORT: 3000

    networks:
      - planta

networks:
  planta:
    driver: bridge
