version: "3.9"

services:
  frontend:
    container_name: pf-planta-pate-web

    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      NODE_ENV: production
      PORT: 3000

    networks:
      - planta

networks:
  planta:
    driver: bridge